import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavBar from "@/Sections/NavBar";
import "./globals.css";

const dmSansSpecific = DM_Sans({
    subsets: ["latin"],
    display: "swap",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: ["normal", "italic"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={dmSansSpecific.className}>
            <body>
                <NavBar />
                {children}
            </body>
        </html>
    );
}

export const metadata: Metadata = {
    title: "Valori",
    description: "Generated by create next app",
};
